server:
 port: 8761
##eureka.instance.status-page-url=http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
eureka:
 server:
  enable-self-preservation: false
 instance:
  hostname: localhost
  prefer-ip-address: true
 client:
  register-with-eureka: false
  fetch-registry: false
 service-url:
  defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
 security:
  user:
   name: admin
   password: admin
   roles: SUPERUSER
logging:
 config: classpath:logback.xml