server:
 port: 10000

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

zuul:
  prefix: "/backend/"  ## 统一前缀
  routes:
    helloServiceConsumer:
      path: /consumer/**
      serviceId: helloServiceConsumer
      retryable: true   ## 是否允许重试 ， 饿汉模式
    helloServiceProvider:
      path: /provider/**
      serviceId: helloServiceProvider
      retryable: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

            spring:
             application:
              name: helloServiceProvider

spring:
  application:
   name: gatewayZuul
  datasource:
    url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 123456
    filters: log4j,wall,mergeStat

logging:
 config: classpath:logback.xml

