host: ${APP_HOST:192.168.0.143}     #localhost
eurekaHost: ${EUREKA_HOST:192.168.0.143}
server:
 port: 10000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 网关服务:${host}:${server.port}
    ip-address: ${host}

  client:
    service-url:
      defaultZone: http://admin:admin@${eurekaHost}:8761/eureka/

zuul:
  prefix: "/backend/"  ## 统一前缀
  routes:
    consumer: ## 名字，任意取
      path: /consumer/**
      serviceId: consumer
      retryable: true   ## 是否允许重试 ， 饿汉模式
    provider: ## 名字，任意取
      path: /provider/**
      serviceId: provider
      retryable: true

 ## 一定要配置ribbon超时时间，否则消费者的服务降级无法实现。例如：A调B，如果B宕机了，如果不配置下面的ribbon超时，则A提供的降级不会执行
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  datasource:
    url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 123456
    filters: log4j,wall,mergeStat
  application:
    name: -gateway-zuul-

logging:
 config: classpath:logback.xml

