host: ${APP_HOST:192.168.0.142}     #localhost
eurekaHost: ${EUREKA_HOST:192.168.0.142}

server:
 port: 9203
eureka:
 instance:
  prefer-ip-address: true
  instance-id: 订单服务:${host}:${server.port}
  ip-address: ${host}
  status-page-url: http://${host}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
 client:
  service-url:
   defaultZone: http://admin:admin@${eurekaHost}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
 application:
  name: provider
 profils:
  active:
   03

 datasource:
      url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: 123456
      filters: log4j,wall,mergeStat
logging:
 config: classpath:logback.xml

dfs:
 client:
   conf: C:/root/client.conf
   host: 39.107.40.76:8089
 max:
   size: 10

