host: 192.168.0.143     #localhost
eurekaHost: 192.168.0.143

server:
  port: 28081

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 网关服务:${host}:${server.port} #将显示在status栏
    ip-address: ${host}   # 服务的ip地址
    status-page-url: http://${host}:${server.port}/swagger-ui.html # 配置swager
  client:
    service-url:
      defaultZone: http://admin:admin@${eurekaHost}:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 123456
    filters: log4j,wall,mergeStat
  application:
    name: cloudgw-service
  cloud:
    gateway:
      routes:
        #- id: jiangzh-predicate
        #uri: "http://www.jd.com"
        #predicates:
        #- After=2018-12-30T23:59:59.789+08:00[Asia/Shanghai]
      - id: path-predicate
        uri: "http://www.jd.com"
        predicates:
        - Path=/jd/**
      - id: consumer-router #微服务
        uri: lb://consumer
        filters:
        - RewritePath=/meetingfilm/consumer/(?<segment>.*), /$\{segment}
        predicates:
        - Path=/meetingfilm/consumer/**
      - id: provider-router #微服务
        uri: lb://provider
        filters:
        - RewritePath=/meetingfilm/provider/(?<segment>.*), /$\{segment}
        predicates:
        - Path=/meetingfilm/provider/**
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 60000



logging:
  config: classpath:logback.xml
