host: 192.168.0.115     #localhost
eurekaHost: 192.168.0.115

server:
  port: 28081

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 网关服务:${host}:${server.port} #将显示在status栏
    ip-address: ${host}   # 服务的ip地址
    status-page-url: http://${host}:${server.port}/swagger-ui.html # 配置swager
  client:
    service-url:
      defaultZone: http://admin:admin@${eurekaHost}:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 123456
    filters: log4j,wall,mergeStat
  application:
    name: cloudgw-service
  cloud:
    gateway:
      routes:
      - id: jiangzh-predicate
        uri: "http://www.jd.com"
        predicates:
        - JiangzhAfter=2018-01-01
        #filters:
        #- Jiangzh=imooc,jiangzh


logging:
  config: classpath:logback.xml
