host: localhost
server:
 port: 8101
eureka:
 instance:
  status-page-url: http://${localhost}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

 client:
  service-url:
   defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
 application:
  name: consumer

 datasource:
      url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: 123456
      filters: log4j,wall,mergeStat

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
 config: classpath:logback.xml

