host: ${APP_HOST:192.168.0.143}     #localhost
eurekaHost: ${EUREKA_HOST:192.168.0.143}
server:
 port: 8101
eureka:
 instance:
  prefer-ip-address: true
  instance-id: 用户服务:${host}:${server.port} #将显示在status栏
  ip-address: ${host}   # 服务的ip地址
  status-page-url: http://${host}:${server.port}/swagger-ui.html # 配置swager

 client:
  service-url:
   defaultZone: http://admin:admin@${eurekaHost}:8761/eureka/
spring:
 application:
  name: consumer

 datasource:
      url: jdbc:mysql://39.107.40.76:3306/meettingfilm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: admin
      password: 123456
      filters: log4j,wall,mergeStat

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
 config: classpath:logback.xml

