mybatis-plus:
  type-aliases-package: com.meettingfilm.backend_common.dao.mapper
  mapper-locations: classpath*:com/meettingfilm/backend_common/dao/mapper/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

server:
   port: 8088
   servlet:
    context-path: /springboot-demo

spring:
  datasource:
    url: jdbc:mysql://120.78.221.149:20000/retire?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: retire
    password: 04wGyfqGZxflDeZR
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
